# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 13:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_auto_20161026_1944'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(default='Sin materia', max_length=100)),
                ('topic', models.CharField(default='Sin Tema', max_length=100)),
                ('time', models.IntegerField(default=0)),
                ('questions', models.IntegerField(default=0)),
            ],
        ),
    ]
