# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0004_exam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exam',
            new_name='ExamModel',
        ),
    ]
