# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-29 14:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0005_auto_20161029_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exammodel',
            old_name='questions',
            new_name='number_of_questions',
        ),
    ]
