# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 17:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_auto_20161029_1108'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammodel',
            name='iterator',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
