# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_selected_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='subject',
            field=models.CharField(default='Type subject', max_length=100),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(default='Type topic', max_length=100),
        ),
    ]
