# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-30 22:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_auto_20161030_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammodel',
            name='result',
            field=models.IntegerField(default=0),
        ),
    ]
